LCA protein	GO number	Description	Category
OG_1087	P:GO:0017183	peptidyl-diphthamide biosynthetic process from peptidyl-histidine	Biological process
OG_1182	C:GO:0016021	integral component of membrane	Molecular function
OG_1323	F:GO:0008080	N-acetyltransferase activity	Molecular function
OG_1327	C:GO:0005643	nuclear pore	Molecular function
OG_1327	P:GO:0016973	poly(A)+ mRNA export from nucleus	Biological process
OG_1349	C:GO:0016020	membrane	Molecular function
OG_1349	P:GO:0016192	vesicle-mediated transport	Molecular function
OG_1378	F:GO:0005515	protein binding	Biological process
OG_1515	F:GO:0004672	protein kinase activity	Biological process
OG_1515	F:GO:0005524	ATP binding	Molecular function
OG_1515	P:GO:0006468	protein phosphorylation	Biological process
OG_1645	F:GO:0005515	protein binding	Biological process
OG_1649	F:GO:0005524	ATP binding	Molecular function
OG_1649	F:GO:0016881	acid-amino acid ligase activity	Molecular function
OG_1649	P:GO:0045116	protein neddylation	Biological process
OG_1706	C:GO:0016020	membrane	Molecular function
OG_1710	F:GO:0005515	protein binding	Biological process
OG_1731	F:GO:0005515	protein binding	Biological process
OG_1793	F:GO:0005515	protein binding	Biological process
OG_1987	F:GO:0003676	nucleic acid binding	Molecular function
OG_2013	F:GO:0015078	proton transmembrane transporter activity	Biological process
OG_2013	P:GO:0015991	ATP hydrolysis coupled proton transport	Molecular function
OG_2013	C:GO:0033177	proton-transporting two-sector ATPase complex, proton-transporting domain	Biological process
OG_2013	C:GO:0033179	proton-transporting V-type ATPase, V0 domain	Biological process
OG_2280	F:GO:0005515	protein binding	Biological process
OG_2414	F:GO:0005515	protein binding	Biological process
OG_3062	P:GO:0006364	rRNA processing	Molecular function
OG_3062	P:GO:0008033	tRNA processing	Molecular function
